### ISSUE TITLE
SQLite/JSON db with events

### ISSUE THREAD

**Issue by t94j0** [sbnietert/westworld-timeline-react#1]
It'd be pretty sweet if you could have an SQLite database or JSON store that contained all the events so that other people could easily add to the project without having to edit Timeline.tsx.

The structure could look something like this:

```
[
  {
    "time": new Date(2020, 6, 2),
    "eventName": "EARLY DAYS OF THE PARK",
    "description": "Arnold and Ford create hosts as they prepare to open Westworld.",
    "involved": [
      {"dolores": "S1E1"},
      {"ford": "S1E2"}
    ]
  },
  ....
]
```

Or something like that. Awesome project.

**Comment by sbnietert** [comment]
That's the plan! Thanks, this is my final project for my sci-fi lit class

**Comment by t94j0** [comment]
Oh, gotcha. I thought this was a personal project. haha

**Comment by t94j0** [comment]
After you submit, lmk, I'd love to help out
